/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bol3_2;

import java.util.Scanner;

public class App {
    

    public static void main(String[] args) {
        
        System.out.print("Introduce una temperatura en grados centígrados: ");
        Scanner objCelsius = new Scanner (System.in);
        float celsius = objCelsius.nextFloat();
        
        float fahrenheit = (float) ((celsius*1.8)+32);
        float kelvin = (float)(celsius+273.15);
        
        System.out.print(celsius+"°C son "+fahrenheit+"°F y "+kelvin+"°K.");
        
        
       
    }
}
