/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bol3_3;

import java.util.Scanner;

public class App {
    
    

    public static void main(String[] args) {
        
        int bil100, bil20, bil5, mon1;
        
        System.out.print("Introduce la cantidad de billetes de 100€ que tienes: ");
        Scanner obj100 = new Scanner (System.in);
        bil100=obj100.nextInt();
        
        System.out.print("Introduce la cantidad de billetes de 20€ que tienes: ");
        Scanner obj20 = new Scanner (System.in);
        bil20=obj20.nextInt();
        
        System.out.print("Introduce la cantidad de billetes de 5€ que tienes: ");
        Scanner obj5 = new Scanner (System.in);
        bil5=obj5.nextInt();
        
        System.out.print("Introduce la cantidad de monedas de 1€ que tienes: ");
        Scanner obj1 = new Scanner (System.in);
        mon1=obj1.nextInt();
        
        int total=(bil100*100)+(bil20*20)+(bil5*5)+(mon1*1);
        
        System.out.print("Si tienes "+bil100+" billetes de 100€, "+bil20+" billetes de 20€, "+bil5+" billetes de 5€ y "+mon1+" monedas de 1€, en total tienes "+total+"€.");
        
        
    }
}
